/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
文件创建成功!
文件创建成功!
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
文件创建成功!
文件创建成功!
文件创建成功!
文件创建成功!
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
---------------------- extra_message ----------------------
Error: dataset file not exists 

---------------------- extra_message ----------------------
Error: dataset file not exists 

---------------------- extra_message ----------------------
Error: dataset file not exists 

---------------------- extra_message ----------------------
Error: dataset file not exists 

---------------------- extra_message ----------------------
Error: dataset file not exists 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry '9' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': '9', 'dataset_name': 'qq', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'q', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry '9' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': '9', 'dataset_name': 'qq', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'q', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'b' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'b', 'dataset_name': 'm', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'm', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry '2' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': '2', 'dataset_name': 'm', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 1, 'introduction': 'm', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
Error: dataset file not exists 

---------------------- extra_message ----------------------
Error: dataset file not exists 

---------------------- extra_message ----------------------
Error: request lacks file 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'b' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'b', 'dataset_name': 'uu', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'u', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'b' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'b', 'dataset_name': 'uu', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'u', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'b' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'b', 'dataset_name': 'uu', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'u', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'b' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'b', 'dataset_name': 'uu', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'u', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'b' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'b', 'dataset_name': 'uu', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'u', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'b' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'b', 'dataset_name': 'uu', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'u', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'b' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'b', 'dataset_name': 'uu', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'u', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'b' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'b', 'dataset_name': 'uu', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'u', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'b' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'b', 'dataset_name': 'uu', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'u', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'b' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'b', 'dataset_name': 'uu', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'u', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'b' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'b', 'dataset_name': 'uu', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 1, 'introduction': 'u', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
Error: request lacks file 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'b' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'b', 'dataset_name': 'uu', 'file_type': '', 'if_profile': 1, 'profile_state': '1', 'task_id': '9f3d3ef9-f987-4699-b137-9de5b7579fa0', 'if_public': 1, 'introduction': 'u', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'b' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'b', 'dataset_name': 'uu', 'file_type': '', 'if_profile': 1, 'profile_state': '1', 'task_id': 'a4146175-104a-4b38-85cf-3631c70f2ac9', 'if_public': 1, 'introduction': 'u', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)文件创建成功!
 

---------------------- extra_message ----------------------
Error: request lacks file 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'b' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'b', 'dataset_name': 'uu', 'file_type': '', 'if_profile': 1, 'profile_state': '1', 'task_id': 'a8552580-4fe2-4873-9062-a575212d970e', 'if_public': 1, 'introduction': 'u', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
Error: request lacks file 

---------------------- extra_message ----------------------
Error: request lacks file 

---------------------- extra_message ----------------------
Error: request lacks file 

---------------------- extra_message ----------------------
Error: request lacks file 

---------------------- extra_message ----------------------
Error: request lacks dataset_id 

---------------------- extra_message ----------------------
Error: request lacks dataset_id 

---------------------- extra_message ----------------------
Error: request lacks dataset_id 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry '6' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': '6', 'dataset_name': 'www', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'w', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry '6' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': '6', 'dataset_name': 'www', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'w', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry '6' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': '6', 'dataset_name': 'www', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': 'w', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'a' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': 'a', 'dataset_name': '08201234', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 0, 'introduction': '08201234', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry '0' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': '0', 'dataset_name': '08201234', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 1, 'introduction': '11', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry '0' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': '0', 'dataset_name': '08201234', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 1, 'introduction': '11', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) 

---------------------- extra_message ----------------------
(pymysql.err.IntegrityError) (1062, "Duplicate entry '0' for key 'dataset.PRIMARY'")
[SQL: INSERT INTO dataset (dataset_id, dataset_name, file_type, if_profile, profile_state, task_id, if_public, introduction, `if_featureEng`, `featureEng_id`, original_dataset_id, user_id, username) VALUES (%(dataset_id)s, %(dataset_name)s, %(file_type)s, %(if_profile)s, %(profile_state)s, %(task_id)s, %(if_public)s, %(introduction)s, %(if_featureEng)s, %(featureEng_id)s, %(original_dataset_id)s, %(user_id)s, %(username)s)]
[parameters: {'dataset_id': '0', 'dataset_name': '08201234', 'file_type': '', 'if_profile': 0, 'profile_state': '0', 'task_id': None, 'if_public': 1, 'introduction': '11', 'if_featureEng': 0, 'featureEng_id': None, 'original_dataset_id': None, 'user_id': '21c4331f8902479b91d6d33d5616d419', 'username': '1'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)文件创建成功!
文件创建成功!
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
文件创建成功!
文件创建成功!
M5
case118
文件创建成功!
M5
case118
文件创建成功!
M5
case118
文件创建成功!
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
M5
case118
文件创建成功!
M4
case300
文件创建成功!
M5
case118
文件创建成功!
M5
case118
文件创建成功!
M5
case118
文件创建成功!
M5
case118
文件创建成功!
M5
case118
文件创建成功!
M5
case118
文件创建成功!
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
M5
case300
文件创建成功!
M5
case300
文件创建成功!
S4
case300
文件创建成功!
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
M5
case300
文件创建成功!
S10
case9241
文件创建成功!
M5
case9241
文件创建成功!
S4
case118
文件创建成功!
M5
case9241
文件创建成功!
S4
case118
文件创建成功!
M5
case9241
文件创建成功!
S4
case118
文件创建成功!
M5
case118
文件创建成功!
M5
case9241
文件创建成功!
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
M5
case300
文件创建成功!
S10
case118
文件创建成功!
S10
case118
文件创建成功!
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
S4
case300
文件创建成功!
/root/HML/celery_tasks/algorithms/_Reinforcementlearning_utils/section_adjust/env
S10
case9241
文件创建成功!
M5
case118
文件创建成功!
S10
case9241
文件创建成功!
M5
case118
文件创建成功!
S10
case118
文件创建成功!
M5
case9241
文件创建成功!
S4
case300
文件创建成功!
M5
case9241
文件创建成功!
